dependencies:
  - name: mariadb
    version: 11.5.1
    repository: "@bitnami"
    tags:
      - mysql
    alias: database
  - name: redis
    version: 17.8.2
    repository: "@bitnami"
    condition: redis.enabled
    tags:
      - redis
