---

- name: Get date
  shell:
    date '+%F'
  register: date
  changed_when: false

- block:
  - name: Create temporary backups directory
    tempfile:
      state: directory
      suffix: backup
    register: backup_dir
  - name: Export WordPress database to file
    shell:
      wp {{ cli_args }} db export "{{ backup_dir.path }}/{{ backup_filename }}"
    # Never overwrite an existing file.
    args:
      creates: "{{ backup_dir.path }}/{{ backup_filename }}"
  - name: Copy export to backup location
    shell:
      rsync -a "{{ backup_dir.path }}/{{ backup_filename }}" "{{ BACKUP_TARGET }}"
  vars:
    backup_filename: "wp-db-{{ BACKUP_NAME }}-{{ date.stdout }}.sql"
