{{- range .Values.ingress.tls }}
{{- if (and .crt .key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    app: {{ include "wordpress.name" $ }}
    chart: {{ include "wordpress.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  tls.crt: {{ .crt | b64enc }}
  tls.key: {{ .key | b64enc }}
type: kubernetes.io/tls
{{- end }}
{{- end }}
