{{- if .Values.wordpress.mu_cron.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "wordpress.fullname" . }}
  labels:
    app: {{ include "wordpress.name" . }}
    chart: {{ include "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- toYaml .Values.wordpress.mu_cron.cronjob.annotations | nindent 4 }}
spec:
  schedule: "{{ .Values.wordpress.mu_cron.cronjob.schedule }}"
  concurrencyPolicy: Forbid
  {{- with .Values.wordpress.mu_cron.cronjob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.wordpress.mu_cron.cronjob.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wordpress.name" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      {{- with .Values.wordpress.mu_cron.cronjob.backoffLimit }}
      backoffLimit: {{ . }}
      {{- end }}
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "wordpress.name" . }}
            app.kubernetes.io/managed-by: {{ .Release.Service }}
        spec:
          # Set a custom service account which has access to the WordPress
          # statefulset's state
          serviceAccountName: {{ include "wordpress.fullname" . }}-account
          restartPolicy: Never
          {{- if (default .Values.image.pullSecrets .Values.wordpress.mu_cron.cronjob.image.pullSecrets) }}
          imagePullSecrets:
          {{- range (default .Values.image.pullSecrets .Values.wordpress.mu_cron.cronjob.image.pullSecrets) }}
            - name: {{ . }}
          {{- end }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}-cron-caller
              image: "{{ default .Values.image.repository .Values.wordpress.mu_cron.cronjob.image.repository }}:{{ default .Values.image.tag .Values.wordpress.mu_cron.cronjob.image.tag }}"
              imagePullPolicy: {{ default .Values.image.pullPolicy .Values.wordpress.mu_cron.cronjob.image.pullPolicy }}
              command: [ "/bin/sh" ]
              args:
                - -c
                - |
                  KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
                  KUBE_NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
                  curl -Sk -H "Authorization: Bearer $KUBE_TOKEN" \
                    https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/$KUBE_NAMESPACE/statefulset/{{ include "wordpress.fullname" . }}

                  # output=$(curl -w '%{http_code}' {{- if .Values.wordpress.mu_cron.cronjob.curlInsecure }} -k {{- end }} --no-progress-meter -L 'http://{{ include "wordpress.fullname" . }}:{{ .Values.service.port }}{{ .Values.wordpress.mu_cron.cronjob.path }}?doing_wp_cron&{{ .Values.wpSalts.WP_CRON_CONTROL_SECRET }}')
                  # If the output is `000`, the service is not running yet. If
                  # the output is exactly 200, the service is working.
                  # Note that if the output is 200invalid secret string, you
                  # need to provide the correct secret!
                  # if [[ "$output" == "000" ]] || [[ "$output" == "200" ]]; then
                  #   echo "success";
                  #   exit 0
                  # else
                  #   echo "failed with output '$output'";
                  #   exit 1
                  # fi
              {{- with .Values.wordpress.mu_cron.cronjob.resources }}
              resources:
                {{ toYaml . | nindent 16 }}
              {{- end }}
    {{- with (default .Values.nodeSelector .Values.wordpress.mu_cron.cronjob.nodeSelector) }}
          nodeSelector:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with (default .Values.affinity .Values.wordpress.mu_cron.cronjob.affinity) }}
          affinity:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with (default .Values.tolerations .Values.wordpress.mu_cron.cronjob.tolerations) }}
          tolerations:
{{ toYaml . | indent 12 }}:
    {{- end }}
{{- end }}
