apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-ansible-secrets
  labels:
    app: {{ include "wordpress.name" . }}
    chart: {{ include "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  secret-vars.yaml: {{ tpl .Values.ansibleSecrets . | b64enc }}
  {{- if .Values.backup.sshPrivateKey }}
  ssh-private-key: {{ .Values.backup.sshPrivateKey | b64enc }}
  ssh-known-hosts: {{ .Values.backup.sshKnownHosts | b64enc }}
  {{- end }}
