apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-ansible-secrets
  labels:
    app: {{ include "wordpress.name" . }}
    chart: {{ include "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  secret-vars.yaml: {{ tpl .Values.ansibleSecrets . | b64enc }}
