---
# Multilingual settings
- name:  Set content directory variable in wp-config
  shell: wp {{ cli_args }} config set  'WP_CONTENT_DIR'  "ABSPATH . 'wp-content'"   --raw --type=constant

- name:  Add wp-config settings for multilingual
  shell: wp {{ cli_args }} config set {{ WP_MULTILINGUAL_CONFIG }}


# Multilingual plugins
- name: Multilingual plugins management block
  block:
    - debug:
        msg: "Trying the configured plugins"
    - name: Activate multilingual plugins if they exist in wp-content-repo 
      shell: wp {{ cli_args }} plugin activate {{ item }}
      with_items: "{{ WP_MULTILINGUAL_PLUGINS }}"
    - debug:
        msg: 'Success'
  rescue:
    - debug:
        msg: 'Multilingual plugins do not exist or error'
    - name: Run wp plugin deativate for all
      shell: wp {{ cli_args }} plugin deactivate {{ item }}
      with_items: "{{ WP_MULTILINGUAL_PLUGINS }}"
    - debug:
        msg: "Multilingual plugins are now deactivated"
